### ISSUE TITLE
malformed edge id error when having node names with underscores

### ISSUE THREAD

**Issue by AlexTereshenkov** [tweag/skyscope#126]
**Describe the bug**

Having a node with an underscore in the name leads to an error in the browser when attempting to expand the hidden nodes by clicking the `Open` link between two nodes:

```
Error: malformed edge id
    at error (30123a11-ba0e-4877-8c4c-ee09f354182d:2021:12)
    at 30123a11-ba0e-4877-8c4c-ee09f354182d:10293:19
    at 30123a11-ba0e-4877-8c4c-ee09f354182d:11707:20
    at run3 (30123a11-ba0e-4877-8c4c-ee09f354182d:4658:25)
    at 30123a11-ba0e-4877-8c4c-ee09f354182d:4955:17
    at drain (30123a11-ba0e-4877-8c4c-ee09f354182d:4538:11)
    at Object.enqueue (30123a11-ba0e-4877-8c4c-ee09f354182d:4556:13)
    at Object.run (30123a11-ba0e-4877-8c4c-ee09f354182d:4954:25)
    at __do5 (30123a11-ba0e-4877-8c4c-ee09f354182d:5545:13)
    at 30123a11-ba0e-4877-8c4c-ee09f354182d:1880:18
```

**To Reproduce**

```
digraph  {
"a/foo.py"
"b/foo.py"
"c/foo_X.py"
"a/foo.py" -> "b/foo.py";
"b/foo.py" -> "c/foo_X.py";
}
```

Working graph (with no underscores in the names of the nodes):

```
digraph  {
"a/foo.py"
"b/foo.py"
"c/foo.py"
"a/foo.py" -> "b/foo.py";
"b/foo.py" -> "c/foo.py";
}
```

![image](https://github.com/tweag/skyscope/assets/50622389/4942c61a-60f2-47a7-8501-7bc78f29156f)

![image](https://github.com/tweag/skyscope/assets/50622389/2f796b9a-4089-4cf8-88e7-c6e61e15be27)

**Expected behavior**

I guess it's reasonable to expect the tool to handle nodes with underscores unless there's a good reason they can't be handled?

**Environment**
 - Version of the code: 0.4.2

**Comment by benradf** [comment]
Thanks for reporting this @AlexTereshenkov.

The problem occurs because [edge ids are formed](https://github.com/tweag/skyscope/blob/f2050bd322b95545c8d5a28d36b87ae26f71215d/backend/src/Render.hs#L155) by joining source and target node ids with an underscore in between. When the front-end tries to recover the node ids by [splitting the edge id](https://github.com/tweag/skyscope/blob/f2050bd322b95545c8d5a28d36b87ae26f71215d/frontend/src/Main.purs#L291-L292), the resulting array will have more than two elements if the node ids contain underscores, and we end up in the `malformed edge id` error case.

I've [fixed it](https://github.com/tweag/skyscope/pull/127) by base64 encoding the node ids before joining them with an underscore, and will create a new release soon.

**Comment by benradf** [comment]
The new release is now available: https://github.com/tweag/skyscope/releases/v0.4.3

Let me know if you encounter any further issues.

**Comment by AlexTereshenkov** [comment]
Thanks a ton, Ben. I confirm the problem's gone away in the latest release.
